n=input('Digite algo ')
print('Isso é número? ')
print(n.isnumeric())
print('Isso é letra? ')
print(n.isalpha())
print('Isso é alfa numérico? ')
print(n.isalnum())
print('Isso é minúsculo? ')
print(n.islower())
print('Isso é maiúsculo? ')
print(n.isupper())
print('Tchau, obrigado!')
